### PR TITLE
midi: fix tuning behavior & ii leader functionality

### LINKED ISSUE #81: Midi output not using tuning table or ii cv functions
See [here](https://llllllll.co/t/ansible-midi-bug-report-tuning-table-not-working/33305). Needs updating to use e.g. `set_cv_note` functions instead of using `dac_set_value` directly.

### PR DESCRIPTION
**Pull request by csboling**
Fixes #81 

* Midi mode will now use the user-customized tuning table and use the ii leader functions for sending pitch info.
* Fixed a bug where tuning mode was not properly exited if you pressed KEY1 on the panel.
* Closing the loop on the tuning issues described in https://github.com/monome/libavr32/pull/54 -- in addition to bringing the tuning table in line with Teletype's, the midi note offset is now applied as a semitone offset rather than an offset in DAC ticks, since a constant-valued offset is not the correct adjustment if the user has applied tuning customizations. To avoid breaking existing presets or Teletype behavior, the offsets are still _stored_ in terms of DAC ticks, but they are quantized to the nearest semitone value from the `ET` table to determine the right adjustment in semitones. Huge thanks to @wolfgangschaltung for helping get to the bottom of this and testing numerous builds.

### CODE REVIEW

File: src/ansible_midi.c [hunk 1]
```diff
@@ -351,8 +336,14 @@ void handler_MidiFrontLong(s32 data) {
 ////////////////////////////////////////////////////////////////////////////////
 ///// common cv utilities
 
-inline static uint16_t pitch_cv(u8 num, s16 offset) {
-	return SEMI14[num] + offset;
+inline static int clamp(int n, int lower, int upper) {
```
Comment (ngwese) [inline src/ansible_midi.c:339]: fwiw the `sclip` (signed clip/clamp) function in libavr32 is the same as `clamp` here (minus the inlining)

Comment (csboling) [reply src/ansible_midi.c]: ...I must have subconsciously done this to ensure symmetry with [my nearly identical remark on your PR from the other day](https://github.com/monome/norns/pull/1156#discussion_r450005568). Fixed in `215706f`
